// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: stt_service.proto

package stt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptRequest) Reset() {
	*x = TranscriptRequest{}
	mi := &file_stt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptRequest) ProtoMessage() {}

func (x *TranscriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptRequest.ProtoReflect.Descriptor instead.
func (*TranscriptRequest) Descriptor() ([]byte, []int) {
	return file_stt_service_proto_rawDescGZIP(), []int{0}
}

func (x *TranscriptRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type TranscriptResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CallId         string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	TranscriptJson string                 `protobuf:"bytes,2,opt,name=transcript_json,json=transcriptJson,proto3" json:"transcript_json,omitempty"` // JSON string
	SttProvider    string                 `protobuf:"bytes,3,opt,name=stt_provider,json=sttProvider,proto3" json:"stt_provider,omitempty"`
	ProcessingTime int32                  `protobuf:"varint,4,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranscriptResponse) Reset() {
	*x = TranscriptResponse{}
	mi := &file_stt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptResponse) ProtoMessage() {}

func (x *TranscriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptResponse.ProtoReflect.Descriptor instead.
func (*TranscriptResponse) Descriptor() ([]byte, []int) {
	return file_stt_service_proto_rawDescGZIP(), []int{1}
}

func (x *TranscriptResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *TranscriptResponse) GetTranscriptJson() string {
	if x != nil {
		return x.TranscriptJson
	}
	return ""
}

func (x *TranscriptResponse) GetSttProvider() string {
	if x != nil {
		return x.SttProvider
	}
	return ""
}

func (x *TranscriptResponse) GetProcessingTime() int32 {
	if x != nil {
		return x.ProcessingTime
	}
	return 0
}

var File_stt_service_proto protoreflect.FileDescriptor

const file_stt_service_proto_rawDesc = "" +
	"\n" +
	"\x11stt_service.proto\x12\x03stt\",\n" +
	"\x11TranscriptRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\"\xa2\x01\n" +
	"\x12TranscriptResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12'\n" +
	"\x0ftranscript_json\x18\x02 \x01(\tR\x0etranscriptJson\x12!\n" +
	"\fstt_provider\x18\x03 \x01(\tR\vsttProvider\x12'\n" +
	"\x0fprocessing_time\x18\x04 \x01(\x05R\x0eprocessingTime2N\n" +
	"\n" +
	"STTService\x12@\n" +
	"\rGetTranscript\x12\x16.stt.TranscriptRequest\x1a\x17.stt.TranscriptResponseB%Z#github.com/salesai/main-api/pkg/sttb\x06proto3"

var (
	file_stt_service_proto_rawDescOnce sync.Once
	file_stt_service_proto_rawDescData []byte
)

func file_stt_service_proto_rawDescGZIP() []byte {
	file_stt_service_proto_rawDescOnce.Do(func() {
		file_stt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stt_service_proto_rawDesc), len(file_stt_service_proto_rawDesc)))
	})
	return file_stt_service_proto_rawDescData
}

var file_stt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stt_service_proto_goTypes = []any{
	(*TranscriptRequest)(nil),  // 0: stt.TranscriptRequest
	(*TranscriptResponse)(nil), // 1: stt.TranscriptResponse
}
var file_stt_service_proto_depIdxs = []int32{
	0, // 0: stt.STTService.GetTranscript:input_type -> stt.TranscriptRequest
	1, // 1: stt.STTService.GetTranscript:output_type -> stt.TranscriptResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stt_service_proto_init() }
func file_stt_service_proto_init() {
	if File_stt_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stt_service_proto_rawDesc), len(file_stt_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stt_service_proto_goTypes,
		DependencyIndexes: file_stt_service_proto_depIdxs,
		MessageInfos:      file_stt_service_proto_msgTypes,
	}.Build()
	File_stt_service_proto = out.File
	file_stt_service_proto_goTypes = nil
	file_stt_service_proto_depIdxs = nil
}
