# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analytics_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61nalytics_service.proto\x12\tanalytics\"\"\n\x0f\x41nalysisRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\"\xcb\x01\n\x10\x41nalysisResponse\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x15\n\rquality_score\x18\x02 \x01(\x05\x12\x14\n\x0cscript_match\x18\x03 \x01(\x05\x12\x13\n\x0b\x65rrors_free\x18\x04 \x01(\x05\x12\x16\n\x0eoverall_rating\x18\x05 \x01(\x01\x12\x0b\n\x03kpi\x18\x06 \x01(\x01\x12\x16\n\x0erecommendation\x18\x07 \x01(\t\x12\r\n\x05\x62rief\x18\x08 \x01(\t\x12\x18\n\x10next_best_action\x18\t \x01(\t2Z\n\x10\x41nalyticsService\x12\x46\n\x0bGetAnalysis\x12\x1a.analytics.AnalysisRequest\x1a\x1b.analytics.AnalysisResponseB+Z)github.com/salesai/main-api/pkg/analyticsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/salesai/main-api/pkg/analytics'
  _globals['_ANALYSISREQUEST']._serialized_start=38
  _globals['_ANALYSISREQUEST']._serialized_end=72
  _globals['_ANALYSISRESPONSE']._serialized_start=75
  _globals['_ANALYSISRESPONSE']._serialized_end=278
  _globals['_ANALYTICSSERVICE']._serialized_start=280
  _globals['_ANALYTICSSERVICE']._serialized_end=370
# @@protoc_insertion_point(module_scope)
