{
 "title": "BullMQ Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Completed Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bullmq_completed_total" }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bullmq_failed_total" }
   ]
  },
  {
   "title": "Waiting Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bullmq_waiting_total" }
   ]
  }
 ]
}