// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: analytics_service.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_analytics_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_analytics_service_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type AnalysisResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CallId         string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	QualityScore   int32                  `protobuf:"varint,2,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	ScriptMatch    int32                  `protobuf:"varint,3,opt,name=script_match,json=scriptMatch,proto3" json:"script_match,omitempty"`
	ErrorsFree     int32                  `protobuf:"varint,4,opt,name=errors_free,json=errorsFree,proto3" json:"errors_free,omitempty"`
	OverallRating  float64                `protobuf:"fixed64,5,opt,name=overall_rating,json=overallRating,proto3" json:"overall_rating,omitempty"`
	Kpi            float64                `protobuf:"fixed64,6,opt,name=kpi,proto3" json:"kpi,omitempty"`
	Recommendation string                 `protobuf:"bytes,7,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Brief          string                 `protobuf:"bytes,8,opt,name=brief,proto3" json:"brief,omitempty"`
	NextBestAction string                 `protobuf:"bytes,9,opt,name=next_best_action,json=nextBestAction,proto3" json:"next_best_action,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_analytics_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_analytics_service_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *AnalysisResponse) GetQualityScore() int32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *AnalysisResponse) GetScriptMatch() int32 {
	if x != nil {
		return x.ScriptMatch
	}
	return 0
}

func (x *AnalysisResponse) GetErrorsFree() int32 {
	if x != nil {
		return x.ErrorsFree
	}
	return 0
}

func (x *AnalysisResponse) GetOverallRating() float64 {
	if x != nil {
		return x.OverallRating
	}
	return 0
}

func (x *AnalysisResponse) GetKpi() float64 {
	if x != nil {
		return x.Kpi
	}
	return 0
}

func (x *AnalysisResponse) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *AnalysisResponse) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *AnalysisResponse) GetNextBestAction() string {
	if x != nil {
		return x.NextBestAction
	}
	return ""
}

var File_analytics_service_proto protoreflect.FileDescriptor

const file_analytics_service_proto_rawDesc = "" +
	"\n" +
	"\x17analytics_service.proto\x12\tanalytics\"*\n" +
	"\x0fAnalysisRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\"\xb5\x02\n" +
	"\x10AnalysisResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12#\n" +
	"\rquality_score\x18\x02 \x01(\x05R\fqualityScore\x12!\n" +
	"\fscript_match\x18\x03 \x01(\x05R\vscriptMatch\x12\x1f\n" +
	"\verrors_free\x18\x04 \x01(\x05R\n" +
	"errorsFree\x12%\n" +
	"\x0eoverall_rating\x18\x05 \x01(\x01R\roverallRating\x12\x10\n" +
	"\x03kpi\x18\x06 \x01(\x01R\x03kpi\x12&\n" +
	"\x0erecommendation\x18\a \x01(\tR\x0erecommendation\x12\x14\n" +
	"\x05brief\x18\b \x01(\tR\x05brief\x12(\n" +
	"\x10next_best_action\x18\t \x01(\tR\x0enextBestAction2Z\n" +
	"\x10AnalyticsService\x12F\n" +
	"\vGetAnalysis\x12\x1a.analytics.AnalysisRequest\x1a\x1b.analytics.AnalysisResponseB+Z)github.com/salesai/main-api/pkg/analyticsb\x06proto3"

var (
	file_analytics_service_proto_rawDescOnce sync.Once
	file_analytics_service_proto_rawDescData []byte
)

func file_analytics_service_proto_rawDescGZIP() []byte {
	file_analytics_service_proto_rawDescOnce.Do(func() {
		file_analytics_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_service_proto_rawDesc), len(file_analytics_service_proto_rawDesc)))
	})
	return file_analytics_service_proto_rawDescData
}

var file_analytics_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_analytics_service_proto_goTypes = []any{
	(*AnalysisRequest)(nil),  // 0: analytics.AnalysisRequest
	(*AnalysisResponse)(nil), // 1: analytics.AnalysisResponse
}
var file_analytics_service_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.GetAnalysis:input_type -> analytics.AnalysisRequest
	1, // 1: analytics.AnalyticsService.GetAnalysis:output_type -> analytics.AnalysisResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_service_proto_init() }
func file_analytics_service_proto_init() {
	if File_analytics_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_service_proto_rawDesc), len(file_analytics_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_service_proto_goTypes,
		DependencyIndexes: file_analytics_service_proto_depIdxs,
		MessageInfos:      file_analytics_service_proto_msgTypes,
	}.Build()
	File_analytics_service_proto = out.File
	file_analytics_service_proto_goTypes = nil
	file_analytics_service_proto_depIdxs = nil
}
