events {
    worker_connections 1024;
}

http {
    upstream main_api {
        server main-api:8080;
    }

    upstream sipuni_listener {
        server sipuni-listener:8081;
    }

    upstream frontend {
        server frontend:80;
    }

    server {
        listen 80;

        # Frontend
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Main API
        location /api/v1 {
            proxy_pass http://main_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Scripts
        location /api/v1/scripts {
            proxy_pass http://script_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Webhooks (AmoCRM)
        location /api/v1/webhooks {
            proxy_pass http://sipuni_listener;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
