events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=30s ipv6=off;
    resolver_timeout 5s;

    upstream main_api {
        server main-api:8080 resolve;
    }

    upstream sipuni_listener {
        server sipuni-listener:8081 resolve;
    }

    upstream frontend {
        server frontend:80 resolve;
    }

    upstream script_service {
        server script-service:8083 resolve;
    }

    upstream sheets_sync {
        server sheets-sync:8085 resolve;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend;
        }

        location /api/v1 {
            proxy_pass http://main_api;
        }

        location /api/v1/scripts {
            proxy_pass http://script_service;
        }

        location /api/v1/webhooks {
            proxy_pass http://sipuni_listener;
        }

        location /api/v1/sheets-sync/ {
            proxy_pass http://sheets_sync/;
        }

        location /minio/ {
            proxy_pass http://minio:9000/;
        }

        location /health {
            access_log off;
            add_header Content-Type text/plain;
            return 200 "OK";
        }
    }
}
