# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stt_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
try:
  from google.protobuf import runtime_version as _runtime_version
except ImportError:  # protobuf < 5.x
  _runtime_version = None
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
if _runtime_version is not None:
  _runtime_version.ValidateProtobufRuntimeVersion(
      _runtime_version.Domain.PUBLIC,
      6,
      31,
      1,
      '',
      'stt_service.proto'
  )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stt_service.proto\x12\x03stt\"$\n\x11TranscriptRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\"m\n\x12TranscriptResponse\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x17\n\x0ftranscript_json\x18\x02 \x01(\t\x12\x14\n\x0cstt_provider\x18\x03 \x01(\t\x12\x17\n\x0fprocessing_time\x18\x04 \x01(\x05\x32N\n\nSTTService\x12@\n\rGetTranscript\x12\x16.stt.TranscriptRequest\x1a\x17.stt.TranscriptResponseB%Z#github.com/salesai/main-api/pkg/sttb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#github.com/salesai/main-api/pkg/stt'
  _globals['_TRANSCRIPTREQUEST']._serialized_start=26
  _globals['_TRANSCRIPTREQUEST']._serialized_end=62
  _globals['_TRANSCRIPTRESPONSE']._serialized_start=64
  _globals['_TRANSCRIPTRESPONSE']._serialized_end=173
  _globals['_STTSERVICE']._serialized_start=175
  _globals['_STTSERVICE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
